name: reaper
base: core18 # the base snap is the execution environment for this snap
version: '609' # just for humans, typically '1.2+git' or '1.3.2'
summary: Reaper
description: |
  REAPER is a complete digital audio production application for computers,
  offering a full multitrack audio and MIDI recording,
  editing, processing, mixing and mastering toolset.
  You can evaluate REAPER in full for 60 days.
  A REAPER license is affordably priced and DRM-free.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: i386
  - build-on: amd64
  - build-on: aarch64
  - build-on: armv7l

parts:
  reaper:
    plugin: dump
    source:
      - on amd64: https://reaper.fm/files/6.x/reaper$SNAPCRAFT_PROJECT_VERSION_linux_x86_64.tar.xz
      - on i386: https://reaper.fm/files/6.x/reaper$SNAPCRAFT_PROJECT_VERSION_linux_i686.tar.xz
      - on aarch64: https://reaper.fm/files/6.x/reaper$SNAPCRAFT_PROJECT_VERSION_linux_aarch64.tar.xz
      - on armv7l:  https://reaper.fm/files/6.x/reaper$SNAPCRAFT_PROJECT_VERSION_linux_armv7l.tar.xz
     stage-packages:

    stage-packages:
      - libpulse0
      - jackd1

apps:
  reaper:
    extensions: [gnome-3-28]
    command: reaper
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$LD_LIBRARY_PATH
    plugs:
      - audio-playback
      - audio-record
      - x11
      - home
      - removable-media
      - desktop
      - desktop-legacy
      - opengl
      - jack1
